print("Here are the multiplication tables upto 12")
for i in range(1, 13):
	print(str(i) + " x 1 = " + str(i*1))
	print(str(i) + " x 1 = " + str(i*2))
	print(str(i) + " x 1 = " + str(i*3))
	print(str(i) + " x 1 = " + str(i*4))
	print(str(i) + " x 1 = " + str(i*5))
	print(str(i) + " x 1 = " + str(i*6))
	print(str(i) + " x 1 = " + str(i*7))
	print(str(i) + " x 1 = " + str(i*8))
	print(str(i) + " x 1 = " + str(i*9))
	print(str(i) + " x 1 = " + str(i*10))
	print("\n\n")